version: '3'

services:
  sonarqube:
    image: sonarqube:10.3-community
    container_name: sonarqube-thesis
    ports:
      - "9000:9000"
    networks:
      - pharmacy_net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

networks:
  pharmacy_net:
    driver: bridge

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
